# Generated by Django 5.0.3 on 2024-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("add_products_img", "0002_product_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to=""),
        ),
    ]
